baseURL: 'https://lasta.github.io/study-elasticsearch-with-ktor/'
languageCode: ja-jp
title: Study Elasticsearch with Ktor
theme: hugo-geekdoc
publishdir: ./publishdir/
hasCJKLanguage: true
useHLJS: true

############################################################
# https://geekdocs.de/usage/getting-started/
############################################################
pluralizeListTitles: false

# Geekdoc required configuration
pygmentsCodeFences: true
pygmentsUseClasses: true
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
