baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "Study Elasticsearch with Ktor"
theme = "hugo-geekdoc"
publishdir = "../build/"

############################################################
# https://geekdocs.de/usage/getting-started/
############################################################
pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
