name: github pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/docs/**'
      - '.github/workflows/gh-pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83'
          extended: true

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies of hugo-geekdoc
        run: npm --prefix ./src/docs/themes/hugo-geekdoc install ./src/docs/themes/hugo-geekdoc

      - name: Install hugo-geekdoc
        run: npx gulp --cwd src/docs/themes/hugo-geekdoc

      - name: Build docs
        run: hugo --source src/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/public
