name: github pages

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: "[debug] show directory layout"
        run: pwd && ls -l

      - name: npm for hugo-geekdoc
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install src/docs/themes/hugo-geekdoc

      - name: npx for hugo-geekdoc
        uses: mikeal/npx@1.0.0
      - run: npx gulp --cwd src/docs/themes/hugo-geekdoc

      - name: Build docs
        run: hugo --minify --source src/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
